export const ADD_UNREAD_NOTIFICATION = 'ADD_UNREAD_NOTIFICATION';
export const REMOVE_NOTIFICATIONS = 'REMOVE_NOTIFICATIONS';
export const PUSH_UNREAD_NOTIFICATIONS = 'PUSH_UNREAD_NOTIFICATIONS';
export const SET_UNREAD_NOTIFICATIONS = 'SET_UNREAD_NOTIFICATIONS';

export const SET_PAST_ONE_DAY_NOTIFS_COUNT = 'SET_PAST_ONE_DAY_NOTIFS_COUNT';
export const SET_LAST_READ_NOTIF = 'SET_LAST_READ_NOTIF';
