export const SET_USER = 'SET_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const SET_USER_ACCEPTED = 'SET_USER_ACCEPTED';
export const SET_USER_STATUS_MSG = 'CHANGE_USER_STATUS_MSG';
export const SET_IS_LOADING = 'SET_IS_LOADING';
export const SET_USER_PORTFOLIO = 'SET_USER_PORTFOLIO';
export const CHANGE_USER_ROLE = 'CHANGE_USER_ROLE';
